### ISSUE TITLE
Cannot find module 'node-sass'

### ISSUE THREAD

**Issue by rajuashok** [forwardemail/email-templates#381]
Hey there, I'm using your lib to send emails from AWS lambda. When I deploy my lambda function I'm getting this error when trying to run render:

```
Failed to render email { Error: Cannot find module 'node-sass'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Module._require.o.require (/var/task/serverless_sdk/index.js:9:90239)
    at require (internal/modules/cjs/helpers.js:25:18)
    at renderSass (/var/task/node_modules/email-templates/lib/template-manager.js:119:14)
    at /var/task/node_modules/email-templates/lib/template-manager.js:69:22
    at Promise._execute (/var/task/node_modules/bluebird/js/release/debuggability.js:411:9)
    at Promise._resolveFromExecutor (/var/task/node_modules/bluebird/js/release/promise.js:518:18)
    at new Promise (/var/task/node_modules/bluebird/js/release/promise.js:103:10)
    at render (/var/task/node_modules/email-templates/lib/template-manager.js:51:10)
    at renderFile (/var/task/node_modules/email-templates/lib/util.js:110:38)
    at /var/task/node_modules/email-templates/lib/email-template.js:273:32
    at tryCatcher (/var/task/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/var/task/node_modules/bluebird/js/release/promise.js:547:31)
    at Promise._settlePromise (/var/task/node_modules/bluebird/js/release/promise.js:604:18)
    at Promise._settlePromiseCtx (/var/task/node_modules/bluebird/js/release/promise.js:641:10)
    at _drainQueueStep (/var/task/node_modules/bluebird/js/release/async.js:97:12) code: 'MODULE_NOT_FOUND' }
```

I know I'm using an old version of email-templates, but thought I'd ask to see if you had any ideas.

**Comment by niftylettuce** [comment]
`yarn add node-sass`?
