### ISSUE TITLE
[fix] CC emails not working if we specify mutiple emails instead of single

### ISSUE THREAD

**Issue by that-spy-kid** [forwardemail/email-templates#451]
## Describe the bug

**Node.js version:** v16.14.1

**OS version:** windows 11

**Description:** 

## Actual behavior
Not working for adding mutilple emails,
-> '[cc_recipient1@example.com](mailto:cc_recipient1@example.com), [cc_recipient2@example.com](mailto:cc_recipient2@example.com)'
-> ['[cc_recipient1@example.com](mailto:cc_recipient1@example.com)', '[cc_recipient2@example.com](mailto:cc_recipient2@example.com)']

## Expected behavior
Working for only sinlge email wrapped in CC,
-> '[cc_recipient1@example.com](mailto:cc_recipient1@example.com)'
->['[cc_recipient1@example.com](mailto:cc_recipient1@example.com)']

## Checklist

- [ ] I have searched through GitHub issues for similar issues.
- [ ] I have completely read through the README and documentation.
- [ ] I have tested my code with the latest version of Node.js and this package and confirmed it is still not working.

**Comment by that-spy-kid** [comment]
Nodemailer Said, 
“ You should probably check it with the email templates project, Nodemailer can send to multiple cc addresses just fine. “

Can you guys check that send() method in the email-templates….. that’s actually causing error! 

This is error Message it’s throwing….
I assignment cc: [ ‘sample1@gmail.com’ , ‘sample2@gmail.com’ ]
 
 Throwing this error for comma-separated string 

Error: Unsuccessful: Status Code: "400" Message: "Bad Request";
"sample1@gmail.com, sample2@gmail.com" is an invalid email address.
    at fn (C:\Temp\micro-v3-main-api-node\node_modules\node-mailjet\mailjet-client.js:326:23)
    at Request.callback (C:\Temp\micro-v3-main-api-node\node_modules\node-mailjet\node_modules\superagent\src\node\index.js:923:3)
    at fn (C:\Temp\micro-v3-main-api-node\node_modules\node-mailjet\node_modules\superagent\src\node\index.js:1153:18)
    at IncomingMessage.<anonymous> (C:\Temp\micro-v3-main-api-node\node_modules\node-mailjet\node_modules\superagent\src\node\parsers\json.js:19:7)

**Comment by that-spy-kid** [comment]
@titanism 

Here is my actually function that I was used to send mails using email-templates!

CODE:
import Email from 'email-templates';
import fs from 'fs';
import nodemailer from 'nodemailer';
import nodemailerMailjet from 'nodemailer-mailjet-transport';

const transport = nodemailer.createTransport(
    nodemailerMailjet({
        auth: {
            apiKey: 'my-key',
            apiSecret: 'my-value',
        },
    }),
);

export const sendMail = async (
    companyId: string,
    emailId: string,
    body: string,
    subject: string,
    CC: string[],
    attachements: Record<string, any>[],
    template?: string,
    otherParams?: Record<string, any>,
) => {
    if (emailId && template) {
        const email = new Email({
            views: { root: __dirname, options: { extension: 'pug' } },
            message: {
                from: 'sample@gmail.com',
            },
            preview: false,
            send: true,
            transport: transport,
        });
        console.log(CC, subject, body, emailId, 'emaiiillll');
        email
            .send({
                template: template,
                message: {
                    cc: CC ? CC : '',
                    to: emailId,
                    attachments: attachements,
                },
                locals: {
                    name: companyId,
                    subject: `${subject}`,
                    body: body,
                    url: 'my-url',
                    ...otherParams,
                },
            })
            .then(() => {
                attachements.length &&
                    attachements.forEach((eachFile: any) => {
                        fs.unlink(`${eachFile.path}`, (err) => {
                            if (err) {
                                logger.error(err);
                            }
                        });
                    });
                console.log(`Email successfully Sent to ${emailId}`);
            })
            .catch((e: any) => {
                console.log(e);
            });
        return { error: false, message: `email successfully Sent to ${emailId}` };
    } else {
        console.log(emailId, 'email');
        console.log(emailId);
        return { error: true, message: `email not sent ${emailId}` };
    }
};

So in message: { cc: }, here I tried all types like the one I mentioned in above!

Can you help me with this sorry for the inconvenience caused by me! 
Thank you so much in advance for your help!

**Comment by that-spy-kid** [comment]
@titanism 
Yes! With just one email in cc like ‘example@you.com' or [‘example@you.com'] working fine but multiple cc email entries not working though! Like this ‘example@you.com,anyother@you.com' or [‘example@you.com', ‘anyother@you.com’, …]  Also I’m accessing attachements from sendMail function parameters not from the parameters from email.send() method! So attachements Fine!
