### ISSUE TITLE
[fix] DeprecationWarning: Calling promisify on a function that returns a Promise is likely a mistake.

### ISSUE THREAD

**Issue by ereator** [forwardemail/email-templates#468]
## Describe the bug

**Node.js version:** 23.2.0

**OS version:** Windows 10 Pro 22H2 19045.5131

**Description:** 
After updating the latest Node, Express and Mail template versions, the error appeared.
1. Once sending an email the Node.js server throws:
(node:13892) [DEP0174] DeprecationWarning: Calling promisify on a function that returns a Promise is likely a mistake.
    at node:internal/util:454:17
    at new Promise (<anonymous>)
    at node:internal/util:439:12
    at Email.render (D:\Projects\uvvo\node_modules\email-templates\index.js:254:47)
    at async Promise.all (index 1)
    at async Email.renderAll (D:\Projects\uvvo\node_modules\email-templates\index.js:268:37)
    at async Email.send (D:\Projects\uvvo\node_modules\email-templates\index.js:338:20)

2. The rendered email in the mailbox looks broken. 
Before update (the desired look):
![image](https://github.com/user-attachments/assets/dfb9cf50-3d19-4613-8ca6-68fae5b91742)
After update (look like the CSS files are ignored now):
![image](https://github.com/user-attachments/assets/32fb9269-69db-48bd-b7c2-68b83d3a1d69)

## Actual behavior
Throws the DeprecationWarning and ignores css files once rendering email

## Expected behavior
Do not throw the DeprecationWarning  and take into consideration the css files as before.

## Code to reproduce

```
const transporter = require('../config/transporter');
const Email = require('email-templates');

const email = new Email({
  message: {from: '"Uvvo" <noreply@uvvo.eu>'},
  send: true,
  preview: false,
  transport: transporter //{jsonTransport: true }
});

async function sendReminder(crm, template, date, notistatus, logMessage) {
    if (crm.user.onNews) {
        mailer.send({
            template,
            message: { to: crm.user.email },
            locals: {
                name: crm.user.first_name,
                email: encrypt(crm.user.email),
                uid:  crm.user._id
            }
        }).catch((err) => {
            console.error('Error sending email:', err);
        });
    }

    crm.notistatus = notistatus;
    crm.comment += `📧 **${date}:** ${logMessage}`;
    console.log(`notify ${notistatus}: `, crm.user.email);
}
```

## Checklist

- [X] I have searched through GitHub issues for similar issues.
- [X] I have completely read through the README and documentation.
- [X] I have tested my code with the latest version of Node.js and this package and confirmed it is still not working.

**Comment by ddequidt** [comment]
This issue has already been reported (#463 and #459) but not fixed.
This comes from https://github.com/forwardemail/email-templates/blob/e8b8cfced71077a9401f6fd03c6ae8369766978a/index.js#L249

Not sure how to solve it as renderFn can be a Promise or nbot dependening on the render engine.

I'm think about using the following instead of util.promisify
```js
const res = await Promise.resolve(() => renderFn(filePath, locals))
```
